### PR TITLE
Homepage - remove Ocotcat when browser height less than 835px

### PR DESCRIPTION
**Pull request by MehmetAdemi**
@JonnyBurger, could you please check if this looks good to you?

It should work however you might have a more efficient approach in removing the Octocat.

If you say everything looks good, then I'm deleting the comments in the code.

### CODE REVIEW

**Comment by JonnyBurger** [comment]
Hmm, this works, but is rather slow, we can handle this much easier with a media query

I'll improve it tomorrow

**Comment by JonnyBurger** [comment]
(I mean the existing `@media` queries which are in the CSS files)

**Comment by MehmetAdemi** [comment]
@JonnyBurger, is it better now?

**Comment by JonnyBurger** [comment]
@MehmetAdemi I am concerned that this now hides it completely on a mobile device - did you test that?

**Comment by MehmetAdemi** [comment]
You were right:




However, I was able to fix it. Should be OK for most of the phones :

**Comment by JonnyBurger** [comment]
Nice! Weird that you are missing the background though 🤔

**Comment by MehmetAdemi** [comment]
The missing background on my phone was just caused by the weird dark mode in the Firefox phone-browser. Test it on Chrome phone-browser, and it works!

Also, I reopened the branch and merged an alternative way where the Ocotocat doesn't disappear but gets behind the HomeBox. Should be fine now.

**Pull request merged**
